import '@kyrian/ui/styles.css'
import { type FC, type PropsWithChildren } from 'react'
import { Inter } from '@next/font/google'

import '../styles/globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Kyrian',
  description: 'Generated by create next app',
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  )
}

export default RootLayout
